### ISSUE TITLE
spec_helper cannot load jukebox file

### ISSUE THREAD

**Issue by kaylee42** [learn-co-curriculum/jukebox-cli#22]
The spec_helper file for the jukebox lesson says: require_relative '../jukebox' RATHER than require_relative '../lib/jukebox' 

This results in the following error message when trying to execute learn: 

```
/Users/kaylee/Development/code/jukebox-cli-web-1115/spec/spec_helper.rb:1:in `require_relative': cannot load such file -- /Users/kaylee/Development/code/jukebox-cli-web-1115/jukebox (LoadError)
	from /Users/kaylee/Development/code/jukebox-cli-web-1115/spec/spec_helper.rb:1:in `<top (required)>'
	from /Users/kaylee/Development/code/jukebox-cli-web-1115/spec/jukebox_spec.rb:1:in `require_relative' 
(etc.)
```

**Comment by SophieDeBenedetto** [comment]
hi @kaylee42, the spec_helper file that I am looking at in this repo says require_relative "../lib/jukebox.rb". You can see that here: https://github.com/learn-co-curriculum/jukebox-cli/blob/master/spec/spec_helper.rb

Perhaps you have an earlier version of this lab, before this problem was fixed? If so, go ahead and remove the repo from your computer with `rm -rf <directory name>` and re-fork and re-clone the lab. 

Feel free to reach out again with any further issues!
