### ISSUE TITLE
Issue with forked/cloned jukebox-cli lab

### ISSUE THREAD

**Issue by jef4490** [learn-co-curriculum/jukebox-cli#33]
Not a question so much as an issue I had (but was able to overcome). When I forked and cloned this lab, some of the files did not seem to come with the directory. Specifically the bin and library directories were empty, and the mp3 files provided were 0 kb nothing files. I was able to "touch jukebox.rb" and copy and paste the raw text from github, but figured I'd share my experience. Not sure if this is something on my end or elsewhere. For the record, I have had no issues of this kind with any other labs.

**Comment by maxwellbenton** [comment]
Hi @jef4490,

Thank you for providing this feedback. I am unfortunately unable to replicate the issue you experienced, but this lesson has recently been updated and is confirmed to be working properly. This lesson uniquely had mp3 files, and these have since been removed, but it is possible these were partially to blame for this issue.

Thank you again for your contribution!
