### ISSUE TITLE
The readme file points to the non existent text in jukebox_spec.rb

### ISSUE THREAD

**Issue by YevgeniySob** [learn-co-curriculum/jukebox-cli#42]
Is the readme file it says
"Check out the following line from our jukebox_spec.rb" and give this code 

it "can use a full song name to find a song" do

but in the jukebox_spec.rb file it slightly spelled differently 

it "can find a song when given a full song name" do

**Comment by maxwellbenton** [comment]
Hi @YevgeniySob,

Thank you for opening this issue! We've updated this lesson's readme and have actually removed this content so that it is only present in the test file.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
